services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: activitypub_toolkit
      POSTGRES_USER: activitypub_toolkit
      POSTGRES_PASSWORD: activitypub_toolkit_pass
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql-data:
