version: '3.7'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: activitypub_toolkit
      POSTGRES_USER: activitypub_toolkit
      POSTGRES_PASSWORD: activitypub_toolkit_pass

    ports:
      - 5432:5432
