from django.urls import path

from ..views import v3

urlpatterns = [
    path("site", v3.LocalSiteView.as_view(), name="site-detail"),
    path("modlog", v3.echo),
    path("search", v3.SearchView.as_view(), name="search"),
    path("resolve_object", v3.ResolveObjectView.as_view(), name="resolve-object"),
    path("community", v3.CommunityView.as_view(), name="community"),
    path("community/hide", v3.echo),
    path("community/list", v3.ListCommunitiesView.as_view(), name="list-communities"),
    path("community/follow", v3.FollowCommunityView.as_view(), name="follow-community"),
    path("community/block", v3.BlockCommunityView.as_view(), name="block-community"),
    path("community/delete", v3.echo),
    path("community/remove", v3.echo),
    path("community/transfer", v3.echo),
    path("community/ban_user", v3.echo),
    path("community/mod", v3.echo),
    path(
        "federated_instances", v3.GetFederatedInstancesView.as_view(), name="federated-instances"
    ),
    path("post", v3.CreatePostView.as_view(), name="create-post"),
    path("post/list", v3.ListPostsView.as_view(), name="list-posts"),
    path("post/delete", v3.DeletePostView.as_view(), name="delete-post"),
    path("post/remove", v3.RemovePostView.as_view(), name="remove-post"),
    path("post/mark_as_read", v3.MarkPostAsReadView.as_view(), name="mark-post-as-read"),
    path("post/lock", v3.LockPostView.as_view(), name="lock-post"),
    path("post/feature", v3.FeaturePostView.as_view(), name="feature-post"),
    path("post/like", v3.PostLikeView.as_view(), name="like-post"),
    path("post/save", v3.SavePostView.as_view(), name="save-post"),
    path("post/report", v3.CreatePostReportView.as_view(), name="create-post-report"),
    path("post/report/resolve", v3.ResolvePostReportView.as_view(), name="resolve-post-report"),
    path("post/report/list", v3.ListPostReportsView.as_view(), name="list-post-reports"),
    path("post/site_metadata", v3.GetSiteMetadataView.as_view(), name="get-site-metadata"),
    path("comment", v3.CreateCommentView.as_view(), name="create-comment"),
    path("comment/list", v3.ListCommentsView.as_view(), name="list-comments"),
    path("comment/delete", v3.DeleteCommentView.as_view(), name="delete-comment"),
    path("comment/remove", v3.RemoveCommentView.as_view(), name="remove-comment"),
    path("comment/mark_as_read", v3.MarkCommentAsReadView.as_view(), name="mark-comment-as-read"),
    path("comment/distinguish", v3.DistinguishCommentView.as_view(), name="distinguish-comment"),
    path("comment/like", v3.CommentLikeView.as_view(), name="like-comment"),
    path("comment/save", v3.SaveCommentView.as_view(), name="save-comment"),
    path("comment/report", v3.CreateCommentReportView.as_view(), name="create-comment-report"),
    path(
        "comment/report/resolve",
        v3.ResolveCommentReportView.as_view(),
        name="resolve-comment-report",
    ),
    path("comment/report/list", v3.ListCommentReportsView.as_view(), name="list-comment-reports"),
    path("private_message", v3.echo),
    path("private_message/list", v3.echo),
    path("private_message/delete", v3.echo),
    path("private_message/mark_as_read", v3.echo),
    path("private_message/report", v3.echo),
    path("private_message/report/resolve", v3.echo),
    path("private_message/report/list", v3.echo),
    path("user", v3.GetPersonDetailsView.as_view(), name="get-person-details"),
    path("user/register", v3.UserRegistrationView.as_view()),
    path("user/get_captcha", v3.echo),
    path("user/mention", v3.echo),
    path("user/mention/mark_as_read", v3.echo),
    path("user/replies", v3.echo),
    path("user/ban", v3.echo),
    path("user/banned", v3.echo),
    path("user/block", v3.echo),
    path("user/login", v3.UserLoginView.as_view(), name="user-login"),
    path("user/delete_account", v3.echo),
    path("user/password_reset", v3.echo),
    path("user/password_change", v3.echo),
    path("user/mark_all_as_read", v3.echo),
    path("user/save_user_settings", v3.echo),
    path("user/change_password", v3.echo),
    path("user/report_count", v3.echo),
    path("user/unread_count", v3.unread_count),
    path("user/verify_email", v3.echo),
    path("user/leave_admin", v3.echo),
    path("user/donation_dialog_shown", v3.echo),
    path("admin/add", v3.echo),
    path("admin/registration_application/count", v3.echo),
    path("admin/registration_application/list", v3.echo),
    path("admin/registration_application/approve", v3.echo),
    path("admin/purge/person", v3.echo),
    path("admin/purge/community", v3.echo),
    path("admin/purge/post", v3.echo),
    path("admin/purge/comment", v3.PurgeCommentView.as_view(), name="purge-comment"),
    path("custom_emoji", v3.echo),
    path("custom_emoji/delete", v3.echo),
    path("site/block", v3.SiteBlockView.as_view()),
    path("user/totp/generate", v3.echo),
    path("user/totp/update", v3.echo),
    path("user/export_settings", v3.echo),
    path("user/import_settings", v3.echo),
    path("user/list_logins", v3.ListLoginsView.as_view(), name="list-logins"),
    path("user/validate_auth", v3.ValidateAuthView.as_view(), name="validate-auth"),
    path("user/logout", v3.LogoutView.as_view(), name="logout"),
    path("post/like/list", v3.ListPostLikesView.as_view(), name="list-post-likes"),
    path("comment/like/list", v3.ListCommentLikesView.as_view(), name="list-comment-likes"),
    path("account/list_media", v3.echo),
    path("admin/list_all_media", v3.echo),
    path("post/hide", v3.HidePostView.as_view(), name="hide-post"),
    path("admin/registration_application", v3.echo),
]
