from django.urls import path

from . import views

urlpatterns = [
    path("api/v4/site", views.SiteView.as_view()),
    path("api/v4/site/icon", views.SiteIconView.as_view()),
    path("api/v4/site/banner", views.SiteBannerView.as_view()),
    # path("api/v4/account", views.GetMyUser.as_view()),
    # path("api/v4/account/auth/get_captcha", views.GetCaptcha.as_view()),
    # path("api/v4/account/auth/login", views.Login.as_view()),
    # path("api/v4/account/auth/logout", views.Logout.as_view()),
    # path("api/v4/account/auth/register", views.Register.as_view()),
    # path("api/v4/account/auth/resend_verification_email",
    # views.ResendVerificationEmail.as_view()),
    # path("api/v4/account/auth/totp/update", views.UpdateTotp.as_view()),
    # path("api/v4/account/auth/verify_email", views.VerifyEmail.as_view()),
    # path("api/v4/account/block/person", views.BlockPerson.as_view()),
    # path("api/v4/account/delete", views.DeleteAccount.as_view()),
    # path("api/v4/account/hidden", views.ListPersonHidden.as_view()),
    # path("api/v4/account/list_logins", views.ListLogins.as_view()),
    # path("api/v4/account/media", views.DeleteMedia.as_view()),
    # path("api/v4/account/media/list", views.ListMedia.as_view()),
    # path("api/v4/account/read", views.ListPersonRead.as_view()),
    # path("api/v4/account/saved", views.ListPersonSaved.as_view()),
    # path("api/v4/account/settings/export", views.ExportSettings.as_view()),
    # path("api/v4/account/settings/import", views.ImportSettings.as_view()),
    # path("api/v4/account/validate_auth", views.ValidateAuth.as_view()),
    # path("api/v4/admin/add", views.AddAdmin.as_view()),
    # path("api/v4/admin/leave", views.LeaveAdmin.as_view()),
    # path(
    #     "api/v4/admin/registration_application/count",
    #     views.GetUnreadRegistrationApplicationCount.as_view(),
    # ),
    # path(
    #     "api/v4/admin/registration_application/list",
    # views.ListRegistrationApplications.as_view()
    # ),
    # path("api/v4/admin/tagline/delete", views.DeleteTagline.as_view()),
    # path("api/v4/admin/tagline/list", views.ListTaglines.as_view()),
    # path("api/v4/admin/users", views.ListUsers.as_view()),
    # path("api/v4/community", views.CommunityView.as_view()),
    # path("api/v4/community/list", views.ListCommunities.as_view()),
    # path("api/v4/community/tag", views.CommunityTagView.as_view()),
    # path("api/v4/federated_instances", views.GetFederatedInstances.as_view()),
    # path("api/v4/image", views.ImageView.as_view()),
    # path("api/v4/image/list", views.ListMediaAdmin.as_view()),
    # path("api/v4/modlog", views.GetModlog.as_view()),
    # path("api/v4/multi_community/follow", views.FollowMultiCommunity.as_view()),
    # path("api/v4/multi_community/list", views.ListMultiCommunities.as_view()),
    # path("api/v4/oauth/authenticate", views.AuthenticateWithOAuth.as_view()),
    # path("api/v4/oauth_provider/delete", views.DeleteOAuthProvider.as_view()),
    # path("api/v4/oauth_provider/edit", views.EditOAuthProvider.as_view()),
    # path("api/v4/person", views.GetPersonDetails.as_view()),
    # path("api/v4/person/content", views.ListPersonContent.as_view()),
    # path("api/v4/post/like", views.LikePost.as_view()),
    # path("api/v4/post/like/list", views.ListPostLikes.as_view()),
    # path("api/v4/post/report", views.CreatePostReport.as_view()),
    # path("api/v4/post/report/resolve", views.ResolvePostReport.as_view()),
    # path("api/v4/post/save", views.SavePost.as_view()),
    # path("api/v4/private_message/report/resolve", views.ResolvePrivateMessageReport.as_view()),
    # path("api/v4/report/list", views.ListReports.as_view()),
]
