# Generated by Django 5.2.9 on 2026-02-03 19:27

import activitypub.core.models.fields
import activitypub.adapters.lemmy.models.aggregates
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activitypub", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LemmyObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(editable=False)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmy_%(class)ss",
                        to="activitypub.reference",
                    ),
                ),
            ],
            options={
                "unique_together": {("reference", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="LocalSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enable_downvotes", models.BooleanField(default=True)),
                ("enable_nsfw", models.BooleanField(default=False)),
                ("community_creation_admin_only", models.BooleanField(default=True)),
                ("require_email_verification", models.BooleanField(default=False)),
                ("application_question", models.TextField(blank=True, null=True)),
                ("private_instance", models.BooleanField(default=False)),
                (
                    "default_theme",
                    models.CharField(
                        choices=[
                            ("browser", "Browser Default"),
                            ("browser_compact", "Browser Default Compact"),
                        ],
                        default="browser",
                        max_length=30,
                    ),
                ),
                (
                    "default_post_listing_type",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Local", "Local"),
                            ("Subscribed", "Subscribed"),
                            ("ModeratorView", "Moderator"),
                        ],
                        default="All",
                        max_length=16,
                    ),
                ),
                ("legal_information", models.TextField(blank=True, null=True)),
                ("hide_modlog_mod_names", models.BooleanField(default=False)),
                ("application_email_admins", models.BooleanField(default=False)),
                ("slur_filter_regex", models.TextField(blank=True, null=True)),
                ("actor_name_max_length", models.PositiveSmallIntegerField(default=40)),
                ("federation_enabled", models.BooleanField(default=False)),
                ("captcha_enabled", models.BooleanField(default=False)),
                (
                    "captcha_difficulty",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "registration_mode",
                    models.CharField(
                        choices=[
                            ("Closed", "Closed"),
                            ("RequireApplication", "Require Application"),
                            ("Open", "Open"),
                        ],
                        default="RequireApplication",
                        max_length=32,
                    ),
                ),
                ("reports_email_admins", models.BooleanField(default=False)),
                ("federation_signed_fetch", models.BooleanField(default=False)),
                ("default_post_listing_mode", models.CharField(default="Card", max_length=16)),
                (
                    "default_sort_type",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Hot", "Hot"),
                            ("New", "New"),
                            ("Old", "Old"),
                            ("TopDay", "Top Day"),
                            ("TopWeek", "Top Week"),
                            ("TopMonth", "Top Month"),
                            ("TopYear", "Top Year"),
                            ("TopAll", "Top All"),
                            ("MostComments", "Most Comments"),
                            ("NewComments", "New Comments"),
                            ("TopHour", "Top Hour"),
                            ("TopSixHour", "Top Sixhour"),
                            ("TopTwelveHour", "Top Twelvehour"),
                            ("TopThreeMonths", "Top Threemonths"),
                            ("TopSixMonths", "Top Sixmonths"),
                            ("TopNineMonths", "Top Ninemonths"),
                            ("Controversial", "Controversial"),
                            ("Scaled", "Scaled"),
                        ],
                        default="Active",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activitypub.language",),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="comment_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("removed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="activitypub_lemmy_adapter.comment",
                        verbose_name="parent",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activitypub_lemmy_adapter.lemmyobject", models.Model),
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="community_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("removed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("Public", "Public"), ("LocalOnly", "Local")],
                        default="Public",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Communities",
            },
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="CustomEmoji",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="emoji_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "keywords",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="person_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                (
                    "blocked_communities",
                    models.ManyToManyField(
                        related_name="blocked_by", to="activitypub_lemmy_adapter.community"
                    ),
                ),
                ("blocked_instances", models.ManyToManyField(to="activitypub.domain")),
                (
                    "liked_comments",
                    models.ManyToManyField(
                        related_name="liked_by", to="activitypub_lemmy_adapter.comment"
                    ),
                ),
                (
                    "moderates",
                    models.ManyToManyField(
                        related_name="moderated_by", to="activitypub_lemmy_adapter.community"
                    ),
                ),
                (
                    "subscribed_communities",
                    models.ManyToManyField(
                        related_name="subscribers", to="activitypub_lemmy_adapter.community"
                    ),
                ),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="post_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("removed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("featured_community", models.BooleanField(default=False)),
                ("featured_local", models.BooleanField(default=False)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="site_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("last_successful_notification_id", models.UUIDField(blank=True, null=True)),
                ("last_successful_published_time", models.DateTimeField(blank=True, null=True)),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("last_retry", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="LemmyContextModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("matrix_user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("remove_data", models.BooleanField(blank=True, null=True)),
                ("locked", models.BooleanField(blank=True, null=True)),
                ("distinguished", models.BooleanField(blank=True, null=True)),
                ("posting_restricted_to_mods", models.BooleanField(blank=True, null=True)),
                (
                    "featured",
                    activitypub.core.models.fields.ReferenceField(editable=False, serialize=False),
                ),
                (
                    "language",
                    activitypub.core.models.fields.ReferenceField(editable=False, serialize=False),
                ),
                (
                    "moderators",
                    activitypub.core.models.fields.ReferenceField(editable=False, serialize=False),
                ),
                (
                    "reference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_context",
                        to="activitypub.reference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LemmyContextModel_featured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
                (
                    "target_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
            ],
            options={
                "db_table": "activitypub_lemmy_adapter_lemmycontextmodel_featured",
            },
        ),
        migrations.CreateModel(
            name="LemmyContextModel_language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
                (
                    "target_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
            ],
            options={
                "db_table": "activitypub_lemmy_adapter_lemmycontextmodel_language",
            },
        ),
        migrations.CreateModel(
            name="LemmyContextModel_moderators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
                (
                    "target_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
            ],
            options={
                "db_table": "activitypub_lemmy_adapter_lemmycontextmodel_moderators",
            },
        ),
        migrations.CreateModel(
            name="LocalSiteRateLimit",
            fields=[
                (
                    "local_site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="rate_limits",
                        serialize=False,
                        to="activitypub_lemmy_adapter.localsite",
                    ),
                ),
                ("message", models.PositiveSmallIntegerField(default=999)),
                ("message_per_second", models.PositiveSmallIntegerField(default=60)),
                ("post", models.PositiveSmallIntegerField(default=999)),
                ("post_per_second", models.PositiveSmallIntegerField(default=600)),
                ("register", models.PositiveSmallIntegerField(default=999)),
                ("register_per_second", models.PositiveSmallIntegerField(default=60)),
                ("image", models.PositiveSmallIntegerField(default=999)),
                ("image_per_second", models.PositiveSmallIntegerField(default=3600)),
                ("comment", models.PositiveSmallIntegerField(default=999)),
                ("comment_per_second", models.PositiveSmallIntegerField(default=600)),
                ("search", models.PositiveSmallIntegerField(default=999)),
                ("search_per_second", models.PositiveSmallIntegerField(default=600)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("import_user_settings", models.PositiveSmallIntegerField(default=99)),
                (
                    "import_user_settings_per_second",
                    models.PositiveSmallIntegerField(default=3600),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalSiteBlockedUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "local_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_urls",
                        to="activitypub_lemmy_adapter.localsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("token", models.TextField(db_index=True, unique=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmy_login_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("answer", models.TextField()),
                ("deny_reason", models.TextField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activitypub.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tagline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "local_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taglines",
                        to="activitypub_lemmy_adapter.localsite",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("show_nsfw", models.BooleanField(default=False)),
                ("theme", models.TextField()),
                (
                    "default_sort_type",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Hot", "Hot"),
                            ("New", "New"),
                            ("Old", "Old"),
                            ("TopDay", "Top Day"),
                            ("TopWeek", "Top Week"),
                            ("TopMonth", "Top Month"),
                            ("TopYear", "Top Year"),
                            ("TopAll", "Top All"),
                            ("MostComments", "Most Comments"),
                            ("NewComments", "New Comments"),
                            ("TopHour", "Top Hour"),
                            ("TopSixHour", "Top Sixhour"),
                            ("TopTwelveHour", "Top Twelvehour"),
                            ("TopThreeMonths", "Top Threemonths"),
                            ("TopSixMonths", "Top Sixmonths"),
                            ("TopNineMonths", "Top Ninemonths"),
                            ("Controversial", "Controversial"),
                            ("Scaled", "Scaled"),
                        ],
                        default="Active",
                        max_length=30,
                    ),
                ),
                (
                    "default_listing_type",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Local", "Local"),
                            ("Subscribed", "Subscribed"),
                            ("ModeratorView", "Moderator"),
                        ],
                        default="Local",
                        max_length=30,
                    ),
                ),
                ("interface_language", models.CharField(default="browser", max_length=20)),
                ("show_avatars", models.BooleanField(default=True)),
                ("send_notifications_to_email", models.BooleanField(default=False)),
                ("show_scores", models.BooleanField(default=True)),
                ("show_bot_accounts", models.BooleanField(default=True)),
                ("show_read_posts", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("accepted_application", models.BooleanField(default=False)),
                ("totp_2fa_secret", models.TextField(blank=True, null=True)),
                ("open_links_in_new_tab", models.BooleanField(default=False)),
                ("blur_nsfw", models.BooleanField(default=True)),
                ("auto_expand", models.BooleanField(default=False)),
                ("infinite_scroll_enabled", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                (
                    "post_listing_mode",
                    models.CharField(
                        choices=[("List", "List"), ("Card", "Card"), ("SmallCard", "Smallcard")],
                        default="List",
                        max_length=30,
                    ),
                ),
                ("totp_2fa_enabled", models.BooleanField(default=False)),
                ("enable_keyboard_navigation", models.BooleanField(default=True)),
                ("enable_animated_images", models.BooleanField(default=True)),
                ("collapse_bot_comments", models.BooleanField(default=False)),
                ("last_donation_notification", models.DateTimeField(null=True)),
                ("show_vote_score", models.BooleanField(default=True)),
                ("show_upvotes", models.BooleanField(default=True)),
                ("show_downvotes", models.BooleanField(default=True)),
                ("show_upvote_percentage", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("languages", models.ManyToManyField(to="activitypub_lemmy_adapter.language")),
            ],
            options={
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AddField(
            model_name="localsite",
            name="discussion_languages",
            field=models.ManyToManyField(blank=True, to="activitypub_lemmy_adapter.language"),
        ),
        migrations.CreateModel(
            name="CommentAggregates",
            fields=[
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="activitypub_lemmy_adapter.comment",
                    ),
                ),
                ("score", models.BigIntegerField(default=1)),
                ("upvotes", models.BigIntegerField(default=1)),
                ("downvotes", models.BigIntegerField(default=0)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("child_count", models.IntegerField(default=0)),
                ("hot_rank", models.FloatField(default=0.0)),
                ("controversy_rank", models.FloatField(default=0.0)),
            ],
            bases=(models.Model, activitypub.adapters.lemmy.models.aggregates.AggregateModelMixin),
        ),
        migrations.CreateModel(
            name="CommunityAggregates",
            fields=[
                (
                    "community",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="activitypub_lemmy_adapter.community",
                    ),
                ),
                ("subscribers", models.BigIntegerField(default=0)),
                ("posts", models.BigIntegerField(default=0)),
                ("comments", models.BigIntegerField(default=0)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("users_active_day", models.BigIntegerField(default=0)),
                ("users_active_week", models.BigIntegerField(default=0)),
                ("users_active_month", models.BigIntegerField(default=0)),
                ("users_active_half_year", models.BigIntegerField(default=0)),
                ("hot_rank", models.FloatField(default=0.0)),
                ("subscribers_local", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="localsite",
            name="custom_emojis",
            field=models.ManyToManyField(blank=True, to="activitypub_lemmy_adapter.customemoji"),
        ),
        migrations.CreateModel(
            name="PersonAggregates",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="counts",
                        serialize=False,
                        to="activitypub_lemmy_adapter.person",
                    ),
                ),
                ("post_count", models.PositiveIntegerField(default=0)),
                ("post_score", models.IntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("comment_score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PostAggregates",
            fields=[
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="activitypub_lemmy_adapter.post",
                    ),
                ),
                ("comments", models.BigIntegerField(default=0)),
                ("score", models.BigIntegerField(default=1)),
                ("upvotes", models.BigIntegerField(default=1)),
                ("downvotes", models.BigIntegerField(default=0)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("newest_comment_time_necro", models.DateTimeField(editable=False, null=True)),
                ("newest_comment_time", models.DateTimeField(editable=False, null=True)),
                ("featured_community", models.BooleanField(default=False)),
                ("featured_local", models.BooleanField(default=False)),
                ("hot_rank", models.FloatField(default=0.0)),
                ("hot_rank_active", models.FloatField(default=0.0)),
                ("controversy_rank", models.FloatField(default=0.0)),
                ("scaled_rank", models.FloatField(default=0.0)),
            ],
            bases=(models.Model, activitypub.adapters.lemmy.models.aggregates.AggregateModelMixin),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmy_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_comments",
                    models.ManyToManyField(
                        related_name="hidden_by", to="activitypub_lemmy_adapter.comment"
                    ),
                ),
                (
                    "read_comments",
                    models.ManyToManyField(
                        related_name="read_by", to="activitypub_lemmy_adapter.comment"
                    ),
                ),
                (
                    "saved_comments",
                    models.ManyToManyField(
                        related_name="saved_by", to="activitypub_lemmy_adapter.comment"
                    ),
                ),
                (
                    "hidden_posts",
                    models.ManyToManyField(
                        related_name="hidden_by", to="activitypub_lemmy_adapter.post"
                    ),
                ),
                (
                    "read_posts",
                    models.ManyToManyField(
                        related_name="read_by", to="activitypub_lemmy_adapter.post"
                    ),
                ),
                (
                    "saved_posts",
                    models.ManyToManyField(
                        related_name="saved_by", to="activitypub_lemmy_adapter.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="liked_posts",
            field=models.ManyToManyField(
                related_name="liked_by", to="activitypub_lemmy_adapter.post"
            ),
        ),
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "_base_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="private_message_data",
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("removed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "lemmyobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activitypub_lemmy_adapter.lemmyobject",
                    ),
                ),
                ("resolved_on", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
            ],
            bases=("activitypub_lemmy_adapter.lemmyobject",),
        ),
        migrations.CreateModel(
            name="SiteReportedStatistics",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="statistics",
                        serialize=False,
                        to="activitypub_lemmy_adapter.site",
                    ),
                ),
                ("users", models.PositiveIntegerField(default=0)),
                ("posts", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("communities", models.PositiveIntegerField(default=0)),
                ("users_active_day", models.PositiveIntegerField(default=0)),
                ("users_active_week", models.PositiveIntegerField(default=0)),
                ("users_active_month", models.PositiveIntegerField(default=0)),
                ("users_active_half_year", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="site_admins", to="activitypub_lemmy_adapter.person"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="allowed_instances",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_lemmy_instances", to="activitypub.domain"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="blocked_instances",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_lemmy_instances", to="activitypub.domain"
            ),
        ),
        migrations.AddField(
            model_name="localsite",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_site",
                to="activitypub_lemmy_adapter.site",
            ),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="activitypub.reference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "reference")},
            },
        ),
        migrations.CreateModel(
            name="PersonPostAggregates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read_comments", models.BigIntegerField(default=0)),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitypub_lemmy_adapter.person",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitypub_lemmy_adapter.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "post")},
            },
        ),
    ]
