steps:
  lint:
    image: python:3.12
    commands:
      - pip install flake8
      - flake8

  test:
    image: python:3.12
    commands:
      - apt-get update
      - pip install uv
      - uv sync --extra dev
      - uv run pytest

when:
  event: [push, pull_request, manual]
